# Generated by Django 5.0.6 on 2026-07-06 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Triaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "frecuencia_respiratoria",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "saturacion_oxigeno",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("nivel_urgencia", models.CharField(blank=True, max_length=32)),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.paciente",
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.personalmedico",
                    ),
                ),
            ],
        ),
    ]
