# Generated by Django 5.0.6 on 2026-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='nivel_urgencia',
            field=models.CharField(blank=True, choices=[('critico', 'Crítico'), ('urgente', 'Urgente'), ('moderado', 'Moderado'), ('normal', 'Normal')], max_length=32),
        ),
    ]
