# Generated by Django 5.0.6 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("historia_clinica", models.CharField(max_length=64, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("nombre_tutor", models.CharField(blank=True, max_length=150)),
                ("telefono_emergencia", models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
