<<<<<<< HEAD
# Generated by Django 5.0.6 on 2026-07-07 02:29
=======
# Generated by Django 5.0.6 on 2026-07-11 23:34
>>>>>>> origin/develop

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
<<<<<<< HEAD
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=1, max_length=1, verbose_name='Sexo'),
=======
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=django.utils.timezone.now, max_length=1, verbose_name='Sexo'),
>>>>>>> origin/develop
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia_clinica',
            field=models.CharField(max_length=64, unique=True, verbose_name='Historia Clínica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Tutor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=32, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarazo_complicado', models.BooleanField(default=False, verbose_name='Embarazo Complicado')),
                ('prematuro', models.BooleanField(default=False, verbose_name='Prematuro')),
                ('peso_nacimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso al Nacer (kg)')),
                ('semanas_gestacion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semanas de Gestación')),
                ('enfermedades_cronicas', models.TextField(blank=True, verbose_name='Enfermedades Crónicas')),
                ('cirugias_previas', models.TextField(blank=True, verbose_name='Cirugías Previas')),
                ('vacunacion_al_dia', models.BooleanField(default=False, verbose_name='Vacunación al Día')),
                ('hospitalizaciones_previas', models.TextField(blank=True, verbose_name='Hospitalizaciones Previas')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_medico', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Médico',
                'verbose_name_plural': 'Antecedentes Médicos',
                'db_table': 'antecedentes_medicos',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Tutor Principal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutores',
            },
        ),
    ]
